[project]
name = "libseraph"
version = "v0.3.2"

authors = [
  { name="Ryan Quinn", email="ryan.quinn@certusinnovations.com" },
]
description = "A multimedia dataset management tool for ML training"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]
license = "MIT"
license-files = ["LICENSE*"]

dependencies = [
    "click ~= 8.3",
    "numpy ~= 2.5",
    "requests ~= 2.32",
    "rich ~= 14.3",
    "soundfile ~= 0.13",
    "tqdm ~= 4.67",
    "tinytag ~= 2.2",
    "torch ~= 2.10",

    "As-A-Person ~= 0.1",
    "AudioMlSpecTools ~= 0.11",
]

[project.optional-dependencies]
coverage = [
    "coverage ~= 7.13",
]

[project.scripts]
seraph = "seraph.main:cli"

[project.urls]
Homepage = "https://github.com/Stonewall-Defense/libseraph"

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["seraph*"]
